# 1 "data/maps/SixIsland_GreenPath/scripts.pory"

# 2 "data/maps/SixIsland_GreenPath/scripts.pory"
SixIsland_GreenPath_MapScripts::
# 3 "data/maps/SixIsland_GreenPath/scripts.pory"
	.byte 0
# 4 "data/maps/SixIsland_GreenPath/scripts.pory"

# 5 "data/maps/SixIsland_GreenPath/scripts.pory"
SixIsland_GreenPath_EventScript_RightRouteSign::
# 6 "data/maps/SixIsland_GreenPath/scripts.pory"
	msgbox SixIsland_GreenPath_Text_LeftRouteSign, MSGBOX_SIGN
# 7 "data/maps/SixIsland_GreenPath/scripts.pory"
	end
# 8 "data/maps/SixIsland_GreenPath/scripts.pory"

# 9 "data/maps/SixIsland_GreenPath/scripts.pory"
SixIsland_GreenPath_EventScript_LeftRouteSign::
# 10 "data/maps/SixIsland_GreenPath/scripts.pory"
	msgbox SixIsland_GreenPath_Text_RightRouteSign, MSGBOX_SIGN
# 11 "data/maps/SixIsland_GreenPath/scripts.pory"
	end
# 12 "data/maps/SixIsland_GreenPath/scripts.pory"

# 13 "data/maps/SixIsland_GreenPath/scripts.pory"
SixIsland_GreenPath_EventScript_Hoenn::
# 14 "data/maps/SixIsland_GreenPath/scripts.pory"
	msgbox SixIsland_GreenPath_Text_Hoenn, MSGBOX_NPC
# 15 "data/maps/SixIsland_GreenPath/scripts.pory"
	end
# 16 "data/maps/SixIsland_GreenPath/scripts.pory"

# 17 "data/maps/SixIsland_GreenPath/scripts.pory"
SixIsland_GreenPath_Text_Hoenn::
# 18 "data/maps/SixIsland_GreenPath/scripts.pory"
	.string "The SEVII ISLANDS share POKéMON\n"
# 19 "data/maps/SixIsland_GreenPath/scripts.pory"
	.string "from KANTO's nearby region,\l"
# 20 "data/maps/SixIsland_GreenPath/scripts.pory"
	.string "JOHTO.\p"
# 21 "data/maps/SixIsland_GreenPath/scripts.pory"
	.string "While the trainers may\n"
# 22 "data/maps/SixIsland_GreenPath/scripts.pory"
	.string "use HOENN POKéMON, none of them\l"
# 23 "data/maps/SixIsland_GreenPath/scripts.pory"
	.string "are found here naturally.\p"
# 24 "data/maps/SixIsland_GreenPath/scripts.pory"
	.string "Tourists bring their\n"
# 25 "data/maps/SixIsland_GreenPath/scripts.pory"
	.string "HOENN POKéMON along with them.$"
