# 1 "data/maps/FiveIsland_LostCave_Room11/scripts.pory"

# 2 "data/maps/FiveIsland_LostCave_Room11/scripts.pory"
FiveIsland_LostCave_Room11_MapScripts::
# 3 "data/maps/FiveIsland_LostCave_Room11/scripts.pory"
	.byte 0
# 4 "data/maps/FiveIsland_LostCave_Room11/scripts.pory"

# 5 "data/maps/FiveIsland_LostCave_Room11/scripts.pory"
FiveIsland_LostCave_Room11_EventScript_Armstrong::
# 6 "data/maps/FiveIsland_LostCave_Room11/scripts.pory"
	lock
# 7 "data/maps/FiveIsland_LostCave_Room11/scripts.pory"
	faceplayer
# 8 "data/maps/FiveIsland_LostCave_Room11/scripts.pory"
	msgbox FiveIsland_LostCave_Room11_Text_Armstrong, MSGBOX_DEFAULT
# 9 "data/maps/FiveIsland_LostCave_Room11/scripts.pory"
	release
# 10 "data/maps/FiveIsland_LostCave_Room11/scripts.pory"
	end
# 11 "data/maps/FiveIsland_LostCave_Room11/scripts.pory"

# 12 "data/maps/FiveIsland_LostCave_Room11/scripts.pory"
FiveIsland_LostCave_Room11_Text_Armstrong:
# 13 "data/maps/FiveIsland_LostCave_Room11/scripts.pory"
	.string "ARMSTRONG: The art of getting\n"
# 14 "data/maps/FiveIsland_LostCave_Room11/scripts.pory"
	.string "lost is passed down through\l"
# 15 "data/maps/FiveIsland_LostCave_Room11/scripts.pory"
	.string "generations of my family!$"
