PalletTown_PlayersHouse_2F_Text_PlayedWithNES::
    .string "{PLAYER} played with the NES.\p"
    .string "…Okay!\n"
    .string "It's time to go!$"

PalletTown_PlayersHouse_2F_Text_PressLRForHelp::
    .string "It's a posted notice…\p"
    .string "If you're confused, ask for HELP!\n"
    .string "Press the L or R Button!$"

PalletTown_PlayersHouse_2F_Text_Version::
	.string "A note is posted on the wall.\n"
	.string "It's a reading from Professor Oak!\p"
	.string "It reads,\n"
	.string "Our readings show that\l"
	.string "We are on Version 1.4!$"
	.string "If your confused on what\n"
	.string "version we are on,\l"
	.string "we are on Version 1.4!$"

PalletTown_PlayersHouse_2F_Text_Normal::
	.string "DIFFICULTY: NORMAL.$"

PalletTown_PlayersHouse_2F_Text_Hard::
	.string "DIFFICULTY: HARD.$"

PalletTown_PlayersHouse_2F_Text_Hardcore::
	.string "DIFFICULTY: HARDCORE.$"
