# 1 "data/maps/SevenIsland_UnusedHouse/scripts.pory"

# 2 "data/maps/SevenIsland_UnusedHouse/scripts.pory"
SevenIsland_UnusedHouse_MapScripts::
# 3 "data/maps/SevenIsland_UnusedHouse/scripts.pory"
	.byte 0
# 4 "data/maps/SevenIsland_UnusedHouse/scripts.pory"

# 5 "data/maps/SevenIsland_UnusedHouse/scripts.pory"
TwoIsland_EventScript_Casey::
# 6 "data/maps/SevenIsland_UnusedHouse/scripts.pory"
	lock
# 7 "data/maps/SevenIsland_UnusedHouse/scripts.pory"
	faceplayer
# 8 "data/maps/SevenIsland_UnusedHouse/scripts.pory"
	msgbox TwoIsland_Text_Casey, MSGBOX_DEFAULT
# 9 "data/maps/SevenIsland_UnusedHouse/scripts.pory"
	release
# 10 "data/maps/SevenIsland_UnusedHouse/scripts.pory"
	end
# 11 "data/maps/SevenIsland_UnusedHouse/scripts.pory"

# 12 "data/maps/SevenIsland_UnusedHouse/scripts.pory"
TwoIsland_Text_Casey:
# 13 "data/maps/SevenIsland_UnusedHouse/scripts.pory"
	.string "I love baseball and\n"
# 14 "data/maps/SevenIsland_UnusedHouse/scripts.pory"
	.string "POKEMON!$"
