# 1 "data/maps/FiveIsland_LostCave_Room13/scripts.pory"

# 2 "data/maps/FiveIsland_LostCave_Room13/scripts.pory"
FiveIsland_LostCave_Room13_MapScripts::
# 3 "data/maps/FiveIsland_LostCave_Room13/scripts.pory"
	.byte 0
# 4 "data/maps/FiveIsland_LostCave_Room13/scripts.pory"

# 5 "data/maps/FiveIsland_LostCave_Room13/scripts.pory"
FiveIsland_LostCave_Room13_EventScript_Oak::
# 6 "data/maps/FiveIsland_LostCave_Room13/scripts.pory"
	lock
# 7 "data/maps/FiveIsland_LostCave_Room13/scripts.pory"
	faceplayer
# 8 "data/maps/FiveIsland_LostCave_Room13/scripts.pory"
	msgbox FiveIsland_LostCave_Room13_Text_Oak, MSGBOX_DEFAULT
# 9 "data/maps/FiveIsland_LostCave_Room13/scripts.pory"
	release
# 10 "data/maps/FiveIsland_LostCave_Room13/scripts.pory"
	end
# 11 "data/maps/FiveIsland_LostCave_Room13/scripts.pory"

# 12 "data/maps/FiveIsland_LostCave_Room13/scripts.pory"
FiveIsland_LostCave_Room13_Text_Oak:
# 13 "data/maps/FiveIsland_LostCave_Room13/scripts.pory"
	.string "OAK: Oh! How did you find me\n"
# 14 "data/maps/FiveIsland_LostCave_Room13/scripts.pory"
	.string "all the way down here?\p"
# 15 "data/maps/FiveIsland_LostCave_Room13/scripts.pory"
	.string "I was just doing some, er…\n"
# 16 "data/maps/FiveIsland_LostCave_Room13/scripts.pory"
	.string "field research. Yes, that's it.$"
